blank_issues_enabled: false
contact_links:
  - name: ðŸ“– Read the README
    url: https://github.com/8bit2qubit/OmniConsole?tab=readme-ov-file
    about: Please read the README documentation for prerequisites and setup.
